_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 55
                - 62
            "4": 3.10.16
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 10
learning_rate:
    value: 0.001
